name: FTP

on: push

jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - name: Install Packages
              run: npm i
            - name: Build GenMapper
              run: npm run build
            - name: 📂 Upload files
              uses: SamKirkland/FTP-Deploy-Action@4.0.0
              with:
                  protocol: ftps
                  server: ${{ secrets.FTP_HOST }}
                  username: ${{ secrets.FTP_USER }}
                  password: ${{ secrets.FTP_PASSWORD }}
